### ISSUE TITLE
DREF - Imminent changes

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#570]
## Task description
Some changes have been requested to the Type of DREF Imminent, please find all the changes in the following document: 
[Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx)

Also, we have developed a document showcasing how the export should look like: 
[DREF for imminent template revision V2 21Dec23.docx](https://github.com/IFRCGo/go-frontend/files/14096262/DREF.for.imminent.template.revision.V2.21Dec23.docx)

Let me know if the document is clear or if you rather I convert the items into a list here in the Github ticket!

@tovari @udaynwa 

## Tickets
- [x] #676
- [x] #698
- [x] #704
- [x] #709
- [x] #705
- [x] #708
- [x] #675 
- [x] #771

**Comment by udaynwa** [comment]
## DEV Questions

- Are there transition rules for different DREF types for different stages of DREF? For example, can a response DREF application change to a Loan DREF type in Ops Update? 
-  Similarly, is there any rule for change in the type of DREF between subsequent Ops Updates? For example, can Ops Update # 2 be an Assessment type if Ops Update # 1 is an Imminent type?
- Does the change in the type of DREF apply to the Final Report?

**Comment by udaynwa** [comment]
## DEV Questions | 02/28/2024
- In the 3rd column of [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx) document, we have `Hide` for some fields, and `Hide from export` for some of the fields (for example: `Previous Operations` field has `Hide`, and `Threshold for early action` field has `Hide from export`. Below is our understanding, please confirm: 
  - `Hide`: Hide from both form and export? 
  - `Hide from export`: Show in form, but hide from export? 
- In the [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx) document, `Request Amount in CHF` is placed in the `Operation Overview` section of the form. But previously, following the [DREF Superticket](https://github.com/IFRCGo/go-web-app/issues/352) we had moved these fields from the `Operation Overview` section to the `Operation ` section. So could you please verify this and let us know what we need to do there? 
- For the `Is the National Society implementing other mitigating measures through other sources of funds?` field in [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx), the first column is empty. Is this also a `New field - long text`? 

@marcovvu1 @anamariaescobar @tovari

**Comment by udaynwa** [comment]
## More questions | 02/28/2024
- `List of activities` field:
  - For the DREF Application, based on the [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx), it says that we will now be having 3 bullet-pointed list of activities text fields (with implementation timeframe) instead of one bullet-pointed list of activities text field. In this case, we have a couple of questions: 
    - What to do with the old `List of activities` data? How do we handle them? 
    - Is the `Implementation timeframe` a mandatory field? If yes, what do we set as a default timeframe for the old `List of activities`?
  - For the DREF Ops Update, the instructions in [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx) are not clear. Could you please review the instructions in the document and clarify? 
- In the 3rd column of the document, when you say 'Leave for the export the field called XYZ only and remove the subtitle', do you mean that we only show the XYZ field in the export and leave out the rest of the fields? For example: `Who will be targeted through this operation?` field, `Explain the selection criteria for the targeted population` field, etc. 

We are happy to discuss all the questions over a few calls too if required. 

cc @marcovvu1 @anamariaescobar @tovari

**Comment by marcovvu1** [comment]
> ## DEV Questions | 02/28/2024
> 
> - In the 3rd column of [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx) document, we have `Hide` for some fields, and `Hide from export` for some of the fields (for example: `Previous Operations` field has `Hide`, and `Threshold for early action` field has `Hide from export`. Below is our understanding, please confirm: 
> 
>   - `Hide`: Hide from both form and export? 
> 
>   - `Hide from export`: Show in form, but hide from export? 
> 
> - In the [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx) document, `Request Amount in CHF` is placed in the `Operation Overview` section of the form. But previously, following the [DREF Superticket](https://github.com/IFRCGo/go-web-app/issues/352) we had moved these fields from the `Operation Overview` section to the `Operation ` section. So could you please verify this and let us know what we need to do there? 
> 
> - For the `Is the National Society implementing other mitigating measures through other sources of funds?` field in [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx), the first column is empty. Is this also a `New field - long text`? 
> 
> 
> 
> @marcovvu1 @anamariaescobar @tovari 

Hi @udaynwa, Thanks for the questions. So, 

On the first point, yes indeed, some of the fields, the ones that are classify as "hide form export" is because we still want to be able to see the information that was added to the field in the on line form, but that information should not make it to the export document. 

On the second point, you are right, the requested amount isn't to longer in the overview and should not be added. 

Hope this helps! 

Marco Vargas

**Comment by marcovvu1** [comment]
@udaynwa 

On you third point, yes that field is also a new long tex field. 

Thanks!

**Comment by marcovvu1** [comment]
What to do with the old `List of activities` data? How do we handle them? - **the list will go into the early action block**

Is the `Implementation timeframe` a mandatory field? If yes, what do we set as a default timeframe for the old `List of activities`? - **no need to add the timeframe to old DREFs**

For the DREF Ops Update, the instructions in [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx) are not clear. Could you please review the instructions in the document and clarify? - **For the export of the ops update, we will display the progress towards outcome field that we have right now where they will explain the progress done so far, but we will also display the field early response block, which will be called Response and it will be where they add the new activities in the update.** 

In the 3rd column of the document, when you say 'Leave for the export the field called XYZ only and remove the subtitle', do you mean that we only show the XYZ field in the export and leave out the rest of the fields? For example: `Who will be targeted through this operation?` field, `Explain the selection criteria for the targeted population` field, etc. - **When we say leave "X" field only, is because we have a case of having fields "X" and "Y" with the same information but one for response "X" and another for early actions "Y", for example the targeting, who are you targeting with response and who with early actions, so what we want to do is to remove the field for early action "Y" form the export, and just show "X", then, because we do not longer have two, we do not need the subtitle, so for example in selection criteria, it should only have the title  selection criteria, and not the "For the expected impacted population if the hazard materialises for the immediate response activities" subtitle.**

Let me know if this helps. 

Marco

@udaynwa @anamariaescobar

**Comment by udaynwa** [comment]
## DEV Questions | 02/29/2024

- According to the [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx), in some of the fields we will now be having two fields where previously there used to be only one field. In this case, how do we handle the data from the previous field? Do we need to map the old field data to the new ones? The fields that have these cases are:
  - Anticipated Needs > Sectors: Previously we had only 1 text field, but now we will be having `Current needs of population at risk` and `Expected needs for immediate assistance if the population is impacted`
  - `Who will be targeted through this operation?` field will be having 2 new sub-fields
  - `Explain the selection criteria for the targeted population` field will be having 2 new sub-fields
  - `Total Targeted Population` field will be having 2 new sub-fields

cc @marcovvu1 @anamariaescobar @tovari

**Comment by udaynwa** [comment]
## DEV Questions | 03/01/2024

- @marcovvu1 , can you also share the export template for DREF Ops Update when DREF Imminent Application transitions to Response type through Ops update? Right now we only received the template for DREF Application when type is Imminent.

cc @tovari @anamariaescobar

**Comment by marcovvu1** [comment]
> ## DEV Questions | 02/29/2024
> 
> - According to the [Changes to Imminent.docx](https://github.com/IFRCGo/go-frontend/files/14096203/Changes.to.Imminent.docx), in some of the fields we will now be having two fields where previously there used to be only one field. In this case, how do we handle the data from the previous field? Do we need to map the old field data to the new ones? The fields that have these cases are:
>   - Anticipated Needs > Sectors: Previously we had only 1 text field, but now we will be having `Current needs of population at risk` and `Expected needs for immediate assistance if the population is impacted`
>   - `Who will be targeted through this operation?` field will be having 2 new sub-fields
>   - `Explain the selection criteria for the targeted population` field will be having 2 new sub-fields
>   - `Total Targeted Population` field will be having 2 new sub-fields
> 
> cc @marcovvu1 @anamariaescobar @tovari 

In this cases, the data from previous applications need to be mapped against the new fields. 

For needs: Current needs of the population at risk

Who will be targeted through this operation: Targeting of population at risk for the early actions

Explain the selection criteria for the targeted population: For population at risk for the early actions

Total targeted population: Early activities

@udaynwa @anamariaescobar

**Comment by udaynwa** [comment]
## Dev Question | 14/03/2024

We have 4 new long text fields added in the `Current National Society Actions`. Our question here is, do we need a `Yes` or `No` boolean input before showing the text fields for these 4 new fields (like we show for `Did the National Society start any anticipatory actions?` 

Currently, we are implementing without the boolean inputs (please check the screenshot). 
![image (2)](https://github.com/IFRCGo/go-web-app/assets/72339626/6c334f71-c437-4055-b0ed-53ee475e031d)


@marcovvu1 @anamariaescobar

**Comment by marcovvu1** [comment]
No need for the yes and no question as this fields will be mandatory @udaynwa @anamariaescobar

**Comment by anamariaescobar** [comment]
Cancelling this ticket due to business change
