### ISSUE TITLE
Disable `Create Final Report` for Loan type

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#635]

**Comment by shraeyaa** [comment]
## Steps to replicate:
- Create DREF application with type - any except Loan
- Approve the DREF application
- Create an operational update
- Change the type of the DREF - Loan
- Approve the DREF operational update

## Expected Behavior
- 'Create final report' option is removed from the options

## Actual Behavior
- 'Create final Report' option was displayed
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/0a7f15f6-eda5-4745-98a5-2b80b25be539)

**Comment by shraeyaa** [comment]
## Steps to replicate:
- Create DREF application with type - Loan
- Approve the DREF application
- Create an operational update
- Change the type of the DREF (any except Loan)
- Approve the DREF operational update

## Expected Behavior
- 'Create final report' option is displayed on the options

## Actual Behavior
- Create final Report option was not displayed

![image](https://github.com/IFRCGo/go-web-app/assets/54019619/3236ae4b-7fc9-4379-906e-48024227a2fe)

@barshathakuri
