### ISSUE TITLE
Implement add/edit local unit functionality

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#856]
### Implementation Details
1. This functionality is only accessible to `Local Unit Admin`.
2. Create an `Add Local Unit` button and open a new form for adding local units when it is clicked.
3. The form should have all the necessary fields and options based on the type of local unit.
4. Once all the required fields are filled, the user can submit the form.
5. The user can access the `Edit Local Unit` form from the local unit popup details section and table actions column.
6. On the `Edit Local Unit` form, all the previous data of the local unit is prefilled.

### Figma
https://www.figma.com/proto/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?page-id=2%3A68604&type=design&node-id=3856-49130&viewport=2538%2C-1789%2C0.28&t=bOW8frnGS6h41erL-1&scaling=scale-down-width&starting-point-node-id=3856%3A49130&hide-ui=1
### User Story
https://docs.google.com/document/d/1fbgCb_KMqWa14oL6wxIU7fO3P--clCFzuIQlC9wYQtk/edit?usp=sharing

**Comment by nanometrenat** [comment]
Can I just check, is the audit trail also implemented, so that superusers can trace back as to who added/changed/deleted what and when?
I'm not sure what the current GO standard is for audit trails in general, but the historic ticket is here:  https://github.com/IFRCGo/go-api/issues/572

Hopefully already implemented as a default part of any build, but commenting a reminder here as a paranoid check!  Thanks a million. cc @tovari

**Comment by samshara** [comment]
@nanometrenat , we will be implementing the audit trail. 

> Hopefully already implemented as a default part of any build, but commenting a reminder here as a paranoid check! Thanks a million. cc @tovari

Do we implement it for all upcoming forms in the future as well?
